Data Toolkit

In [ ]:
1. What is NumPy, and why is it widely used in Python?

      # NumPy (short for Numerical Python) is a powerful library in Python that
       is widely used for numerical and scientific computing. It provides support
       for large, multi-dimensional arrays and matrices, along with a collection
       of high-level mathematical functions to operate on these arrays.
       Overall, NumPy simplifies and speeds up mathematical computations,
       and it's essential for anyone working with large datasets or
       complex mathematical operations in Python.


2. How does broadcasting work in NumPy?

      # When performing operations between two arrays (like addition,
        multiplication, etc.), NumPy checks if the arrays' shapes are compatible.
        If they are, NumPy "broadcasts" the smaller array to match the larger
        array’s shape. Broadcasting follows a set of rules that determine
        whether two arrays can be broadcast together:

3. What is a Pandas DataFrame?

      # A Pandas DataFrame is one of the most commonly used data structures
        in Python, provided by the Pandas library. It is essentially
        a 2-dimensional table (like a spreadsheet or a SQL table) where data is
        stored in rows and columns. Each column can have a different data type
         (e.g., integers, floats, strings), making it extremely versatile for
          working with structured data.

4. Explain the use of the groupby() method in Pandas?

      # The groupby() method in Pandas is a powerful and versatile tool for
        splitting, applying, and combining data. It allows you to group your
        data based on some criteria (e.g., by column values) and then perform
        aggregate functions (like sum, mean, count, etc.) on those groups.
        This method is essential for data aggregation and summarization,
        especially when dealing with large datasets.

5. Why is Seaborn preferred for statistical visualizations?

      # Seaborn is preferred for statistical visualizations because it offers
        an easy-to-use interface for creating complex statistical plots with
        minimal effort, particularly for those working with Pandas DataFrames.
        It integrates statistical functions, handles categorical data gracefully,
        provides attractive default styles, and offers a wide range of high-level
        plotting functions that are perfect for exploratory data analysis and
        statistical visualization. These features make Seaborn a go-to choice
        for anyone looking to create clear, informative, and statistically
        meaningful visualizations in Python.

6. What are the differences between NumPy arrays and Python lists?

      # Python
        > Heterogeneous (can store mixed types)
        > Less memory efficient
        > Slower for large data sets
        > Requires loops for element-wise operations
        > Difficult to handle with nesting
        > Requires manual effort

      # Numpy Arrays
        > Homogeneous (single data type)
        > More memory efficient
        > Faster, optimized for numerical data
        > Supports element-wise operations directly
        > Supports multi-dimensional arrays easily
        > Supports reshaping and broadcasting

7. What is a heatmap, and when should it be used?

      # A heatmap is a data visualization technique that represents data in a
        two-dimensional matrix format, where the individual values in a matrix
        are represented by colors. These colors help to convey the magnitude or
        intensity of values in the dataset. Heatmaps are widely used in various
        fields such as statistics, data analysis, machine learning, and
        geographical mapping.

# In a heatmap:

Color intensity (or gradient) represents the values of the data, with lighter or
darker shades indicating higher or lower values, depending on the color scheme used.
It’s often used to display correlations, frequency distributions, or
geospatial data, allowing users to easily identify patterns, trends, and outliers.


8. What does the term “vectorized operation” mean in NumPy?

      # In NumPy, the term "vectorized operation" refers to the ability to
        perform element-wise operations on arrays without the need for explicit
        loops. Essentially, it means that operations on entire arrays
        (or large chunks of data) can be carried out in parallel at a low level,
        allowing for more efficient computation. These operations leverage
        highly optimized C code under the hood, resulting in significant
        performance improvements over traditional Python loops.

9.  How does Matplotlib differ from Plotly?

      # Matplotlib
      > Mostly static; limited interactivity
      > More verbose, low-level customization
      > Mostly 2D, some 3D support
      > Highly customizable, more control
      > Faster for static plots
      > Ideal for static reports and papers
      > Static images (PNG, SVG, PDF, etc.)
      > Scientific plots, static reports

      # Plotly
      > Built for interactive, web-based plots
      > High-level API, easier for quick visualizations
      > Both 2D and 3D, interactive charts, maps
      > Good customization, less fine control
      > Slower for large datasets due to interactivity overhead
      > Best for dashboards, web apps, and interactive visuals
      > Interactive HTML (can be embedded)
      > Dashboards, business analysis, data apps

10. What is the significance of hierarchical indexing in Pandas?

        > Multi-dimensional structure: Organize and access data by multiple keys
         (levels).
        > Efficient grouping and aggregation: Perform sophisticated group
          operations with multiple levels.
        > Improved data access: Select data more easily based on specific
          hierarchical indices.
        > Enhanced data representation: Useful for complex, hierarchical data
         (e.g., multi-level categories).
        > Increased flexibility: Allows reshaping, sorting, and restructuring
          data with ease.

11. What is the role of Seaborn’s pairplot() function?

       # The pairplot() function in Seaborn is used to create pairwise
         scatterplots of multiple numerical variables in a dataset,
         offering a way to visualize the relationships between all pairs of
         variables. This function is especially useful for exploring potential
         correlations, distributions, and patterns in the data, as it generates
         a grid of scatterplots for each pair of numerical columns. It can also
         provide histograms or density plots on the diagonal to represent the
          distribution of each individual variable.

12. What is the purpose of the describe() function in Pandas?

       #  The describe() function in Pandas is used to generate summary
          statistics of the numerical columns in a DataFrame or Series.
          It provides a quick overview of the central tendency, spread,
          and shape of the distribution of the data. This function is
          particularly useful during Exploratory Data Analysis (EDA),
          as it gives insight into the characteristics of the dataset,
          helping you understand its structure before performing further analysis.

13. Why is handling missing data important in Pandas?

       # Handling missing data is a crucial step in data cleaning and
         preprocessing in Pandas (and in any data analysis workflow)
         because missing values can significantly impact the quality
         and accuracy of your analysis and models. Pandas provides powerful
         tools to detect, handle, and fill missing data in a variety of ways
          to ensure your dataset is clean, consistent, and ready for analysis.

14. What are the benefits of using Plotly for data visualization?

        # Summary of Benefits:
        > Interactive visualizations make data exploration easier.
        > High-quality visuals for presentation and reporting.
        > Wide range of chart types including 3D and geospatial visualizations.
        > Easy integration with Python and other languages.
        > Customization options to control the appearance and behavior of the plot.
        > Great support for web-based applications and dashboards.
        > Export options for both static and interactive formats.
        > Active community and comprehensive documentation.

15. How does NumPy handle multidimensional arrays?

        # Summary of Key Operations for Multidimensional Arrays:
        > Creation: np.array()
        > Shape and dimension: .shape, .ndim
        > Indexing: arr[row, col] (and more for higher dimensions)
        > Slicing: arr[start:stop]
        > Reshaping: .reshape()
        > Element-wise operations: Direct mathematical operations (e.g., arr + 1)
        > Broadcasting: Automatic handling of different shapes during operations
        > Aggregation: np.sum(), np.mean(), etc., with axis argument
        > Concatenation: np.concatenate()
        > Filtering: Boolean indexing
        NumPy's handling of multidimensional arrays makes it an efficient and
        powerful tool for scientific computing, data analysis, and
        machine learning tasks, allowing for seamless operations on complex datasets.

16. Explain the difference between apply() and map() in Pandas?

      # apply()
      > Works with both Series and DataFrames.
      > Can apply any function (including functions involving multiple columns
                                or custom logic).
      > More flexible, especially with DataFrames.
      > Can apply a function along a specified axis (rows or columns)
        in a DataFrame.
      > Returns a Series (if applied to a Series) or a DataFrame
        (if applied to a DataFrame).
      > Generally slower compared to map() because it can handle more complex operations.

      # map()
      > Works only with Series.
      > Works with functions, dictionaries, or Series.
      > Limited to element-wise transformations on Series.
      > Does not support axis specification.
      > Returns a Series (with transformed values).
      > Faster than apply() for simple element-wise transformations.

17. What is the role of Bokeh in data visualization?

      # Bokeh is a powerful interactive data visualization library in Python
       that allows users to create interactive and visually appealing plots
        and dashboards. It is particularly well-suited for creating web-based
         visualizations that can be easily embedded into web applications.
         The key strength of Bokeh is its ability to generate highly interactive
         plots, which can be customized and controlled in real-time, making it
         a popular choice for both data exploration and presentation.

18. What are some advanced features of NumPy?

      # NumPy’s advanced features, including broadcasting, vectorized operations,
        linear algebra, and memory-mapped files, make it an essential tool for
        scientific computing, data analysis, and machine learning.
        These capabilities allow users to handle large datasets, perform
        complex mathematical operations, and leverage high-performance computing
        efficiently. Whether you're working with multidimensional arrays,
        statistical functions, or optimizing performance for large-scale
        computations, NumPy has the tools necessary to support your needs.

19.  How does Pandas simplify time series analysis?

      # Pandas simplifies time series analysis by providing powerful,
      high-level tools specifically designed to handle datetime and
      time-based data. Time series data is crucial for many applications,
      such as financial data analysis, sensor data, and forecasting, and
      Pandas makes it easier to work with, manipulate, and analyze this type of data.

20. What is the role of a pivot table in Pandas?

     # Group and Aggregate Data: Pivot tables allow you to group data by one
       or more categorical columns and then compute statistics
        (such as sum, mean, count) on the grouped data.
       Flexibility in Aggregation: You can perform different aggregation functions
        (e.g., sum, mean, count, min, max, etc.) on the data within each group.
       Multi-Level Indexing: You can create pivot tables with multi-level
        indices for more complex aggregations.

21. Why is NumPy’s array slicing faster than Python’s list slicing?

      # NumPy's array slicing is faster than Python's list slicing due to its
        contiguous memory allocation, optimized C implementation,
        viewing mechanism (no new copy of data unless required), and its use of
        strides for efficient access to elements. These optimizations,
        along with the ability to avoid unnecessary memory copying, make NumPy
        slicing much more efficient than Python list slicing, especially for
         large datasets.

22. What are some common use cases for Seaborn?

     # Seaborn is a highly versatile library that simplifies creating visually
      appealing and informative statistical plots. It is widely used for:

     > Exploratory Data Analysis (EDA)
     > Visualizing distributions and relationships
     > Comparing categorical and numerical data
     > Handling time series data
     > Creating complex statistical plots like pair plots and heatmaps







Practical




In [ ]:
1.  How do you create a 2D NumPy array and calculate the sum of each row?

import numpy as np

# Step 1: Create a 2D NumPy array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Step 2: Calculate the sum of each row (axis=1 sums along rows)
row_sums = array_2d.sum(axis=1)

print("2D Array:")
print(array_2d)

print("\nSum of each row:")
print(row_sums)

Output
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of each row:
[ 6 15 24]

2. Write a Pandas script to find the mean of a specific column in a DataFrame

import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 55000, 60000, 65000, 70000]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Calculate the mean of the 'Age' column
mean_age = df['Age'].mean()

# Print the result
print(f"The mean age is: {mean_age}")

# Calculate the mean of the 'Salary' column
mean_salary = df['Salary'].mean()

# Print the result
print(f"The mean salary is: {mean_salary}")

Output

The mean age is: 35.0
The mean salary is: 61000.0

3. Create a scatter plot using Matplotlib

import matplotlib.pyplot as plt

# Sample data
x = [1, 2, 3, 4, 5]
y = [2, 4, 5, 7, 11]

# Create a scatter plot
plt.scatter(x, y, color='blue', marker='o', label='Data Points')

# Add title and labels
plt.title("Scatter Plot Example")
plt.xlabel("X-axis")
plt.ylabel("Y-axis")

# Show the legend
plt.legend()

# Display the plot
plt.show()

When you run this code, a scatter plot will appear with data points
at (1, 2), (2, 4), (3, 5), (4, 7), and (5, 11). You can customize
the appearance of the plot by changing colors, markers, or adding more
elements like grid lines or annotations.

4. How do you calculate the correlation matrix using Seaborn and visualize it
with a heatmap

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

# Sample DataFrame
data = {
    'A': [1, 2, 3, 4, 5],
    'B': [5, 4, 3, 2, 1],
    'C': [2, 3, 4, 5, 6],
    'D': [5, 3, 2, 1, 0]}

df = pd.DataFrame(data)

# Step 1: Calculate the correlation matrix
correlation_matrix = df.corr()

# Step 2: Create a heatmap using Seaborn
plt.figure(figsize=(8, 6))  # Set the size of the plot
sns.heatmap(correlation_matrix, annot=True, cmap="coolwarm", fmt='.2f', linewidths=0.5)

# Display the plot
plt.title("Correlation Matrix Heatmap")
plt.show()

output

The cells will show the correlation values between each pair of columns.
The color scale will indicate the strength of the correlation, with cooler
colors representing negative correlations and warmer colors representing
positive correlations.


5. Generate a bar plot using Plotly

import plotly.express as px

# Sample data
data = {
    'Category': ['A', 'B', 'C', 'D', 'E'],
    'Value': [23, 45, 56, 78, 33]
}

# Create a DataFrame
import pandas as pd
df = pd.DataFrame(data)

# Create a bar plot using Plotly
fig = px.bar(df, x='Category', y='Value', title='Bar Plot Example')

# Show the plot
fig.show()

Output:
This will generate an interactive bar plot where the categories 'A', 'B', 'C', 'D',
and 'E' are displayed on the x-axis, and their corresponding values are plotted
as bars on the y-axis. Plotly's interactive features allow you to hover over the
bars for more details, zoom in/out, and pan the chart.


6. Create a DataFrame and add a new column based on an existing column

import pandas as pd

# Step 1: Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 55000, 60000, 65000, 70000]
}

df = pd.DataFrame(data)

# Step 2: Add a new column based on the 'Age' column
# Let's create a new column 'Age Group' based on the 'Age' column
df['Age Group'] = ['Young' if age < 30 else 'Middle-aged' for age in df['Age']]

# Display the updated DataFrame
print(df)

Output:
      Name  Age  Salary    Age Group
0    Alice   25   50000        Young
1      Bob   30   55000  Middle-aged
2  Charlie   35   60000  Middle-aged
3    David   40   65000  Middle-aged
4      Eva   45   70000  Middle-aged

7. Write a program to perform element-wise multiplication of two NumPy arrays

import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])

# Perform element-wise multiplication
result = array1 * array2

# Print the result
print("Array 1:", array1)
print("Array 2:", array2)
print("Element-wise multiplication result:", result)

Output
Array 1: [1 2 3 4 5]
Array 2: [5 4 3 2 1]
Element-wise multiplication result: [5 8 9 8 5]

8. Create a line plot with multiple lines using Matplotlib

import matplotlib.pyplot as plt

# Sample data for multiple lines
x = [0, 1, 2, 3, 4, 5]

# Define multiple y datasets
y1 = [0, 1, 4, 9, 16, 25]  # y = x^2
y2 = [0, 1, 2, 3, 4, 5]    # y = x
y3 = [0, 2, 4, 6, 8, 10]   # y = 2x

# Create a line plot with multiple lines
plt.plot(x, y1, label='y = x^2', color='b', marker='o')
plt.plot(x, y2, label='y = x', color='g', marker='s')
plt.plot(x, y3, label='y = 2x', color='r', marker='^')

# Add title and labels
plt.title('Multiple Line Plot Example')
plt.xlabel('X-axis')
plt.ylabel('Y-axis')

# Show legend to label each line
plt.legend()

# Display the plot
plt.show()

Output:
This will generate a plot with three lines:

A blue line representing y=x^2,
A green line representing y=x,
A red line representing y=2x.

9. Generate a Pandas DataFrame and filter rows where a column value is greater
than a threshold

import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age': [25, 30, 35, 40, 45],
    'Salary': [50000, 55000, 60000, 65000, 70000]}

# Create DataFrame
df = pd.DataFrame(data)

# Define the threshold for the 'Salary' column
threshold = 60000

# Filter rows where 'Salary' is greater than the threshold
filtered_df = df[df['Salary'] > threshold]

# Display the filtered DataFrame
print(filtered_df)

Output
      Name  Age  Salary
2  Charlie   35   60000
3    David   40   65000
4      Eva   45   70000

10. Create a histogram using Seaborn to visualize a distribution

import seaborn as sns
import matplotlib.pyplot as plt

# Sample data
data = [23, 45, 56, 78, 33, 45, 67, 89, 34, 56, 23, 45, 67, 34, 56]

# Create a histogram using Seaborn
sns.histplot(data, bins=10, kde=True, color='blue', edgecolor='black')

# Add title and labels
plt.title('Histogram of Sample Data')
plt.xlabel('Value')
plt.ylabel('Frequency')

# Display the plot
plt.show()

The resulting plot will show a histogram of the data with 10 bins, a Kernel
 Density Estimate (smoothed curve) overlaid, and labeled axes.

This histogram is useful for understanding the distribution of a single variable
 and identifying patterns such as skewness or multi-modal distributions.

11. Perform matrix multiplication using NumPy

import numpy as np

# Define two matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot()
result = np.dot(A, B)

# Alternatively, you can use the @ operator for matrix multiplication
# result = A @ B

# Display the result
print("Matrix A:")
print(A)

print("Matrix B:")
print(B)

print("Matrix multiplication result:")
print(result)

Output
Matrix A:
[[1 2]
 [3 4]]
Matrix B:
[[5 6]
 [7 8]]
Matrix multiplication result:
[[19 22]
 [43 50]]

12. Use Pandas to load a CSV file and display its first 5 rows

import pandas as pd

# Load the CSV file into a DataFrame
# Make sure to replace 'your_file.csv' with the actual path to your CSV file
df = pd.read_csv('your_file.csv')

# Display the first 5 rows
print(df.head())

13. Create a 3D scatter plot using Plotly

import plotly.express as px
import pandas as pd

# Sample data for 3D scatter plot
data = {
    'X': [1, 2, 3, 4, 5],
    'Y': [10, 11, 12, 13, 14],
    'Z': [100, 200, 300, 400, 500],
    'Color': ['red', 'green', 'blue', 'purple', 'orange']
}

# Create a DataFrame from the sample data
df = pd.DataFrame(data)

# Create a 3D scatter plot
fig = px.scatter_3d(df, x='X', y='Y', z='Z', color='Color', title='3D Scatter Plot')

# Show the plot
fig.show()

Output
This will generate an interactive 3D scatter plot where each point corresponds
to a coordinate from the X, Y, and Z columns. The points will be color-coded
according to the values in the 'Color' column, and you'll be able to rotate
 and zoom into the plot.
